[package]
name = "dic"
version = "0.5.0"
authors = ["Frank Wiles <frank@revsys.com>"]
edition = "2024"
rust-version = "1.85"
description = "Remove local Docker images using simple text matching"
license = "BSD-3-Clause"
repository = "https://github.com/frankwiles/dic"

[profile.dev]
split-debuginfo = "unpacked"
debug = false

[dependencies]
anyhow = "1.0"
bollard = "0.21"
clap = { version = "4.6", features = ["derive"] }
humansize = "2.1"
rprompt = "2.2"
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }
